Update build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,34 +1,58 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
+# shellcheck disable=SC2059
+log_normal() {
+	if [ $# -gt 0 ]; then
+		printf "$@" >&2
+	fi
+	printf "\n" >&2
+}
+
+# shellcheck disable=SC2059
+log_underlined() {
+	line="$(printf "$@")"
+	printf "%s\n" "${line}" >&2
+	printf "%s\n" "${line//?/=}" >&2
+}
+
 if [[ "$#" -lt 1 ]]; then
-    echo "Usage: $0 <scope: full|all> [prefix]"
-    exit 1
+	log_normal "Usage: $0 <scope: full|all> [prefix]"
+	exit 1
 fi
 
 scope="$1"
 prefix="${2:-}"
 
 case "$scope" in
-  all|full|net|hft|python)
-    ;;
-  *)
-    echo "Error: scope must be one of 'all', 'full', 'net', 'hft', or 'python'"
-    exit 1
-    ;;
+	all|full|net|hft|python)
+		;;
+	*)
+		log_normal "Error: scope must be one of 'all', 'full', 'net', 'hft', or 'python'"
+		exit 1
+		;;
 esac
 
 cd "$(dirname "$0")"
 mkdir -p output
 
 build_file() {
+	log_underlined "PROCESSING '$1'"
 	tectonic -Z search-path=. -o output "examples/$1.tex"
 	prefixed_name="$1"
 	if [[ -n "$prefix" ]]; then
 		prefixed_name="$prefix-$1"
 		mv "output/$1.pdf" "output/$prefixed_name.pdf"
 	fi
-	pdftoppm -singlefile -png -r 300 "output/$prefixed_name.pdf" "output/$prefixed_name"
+	log_normal "DONE"
+
+	log_normal
+	log_underlined "CREATING PNG FOR '$1'"
+	pdftoppm -singlefile -png -r 300 "output/$prefixed_name.pdf" "output/$prefixed_name" 2> >(
+		# Suppress warnings due to poppler bug: https://gitlab.freedesktop.org/poppler/poppler/-/issues/1524
+		grep -v -E "Couldn't link the profiles|Can't create Lab transform" >&2
+	)
+	log_normal "DONE"
 }
 
 if [[ "$scope" == "full" || "$scope" == "all" ]]; then
